name: Build C++

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: g++ main.cpp -std=c++17 -Wall -Wextra -Werror -o sampleCI
